server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/keshe?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #thymeleaf配置
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
